### ISSUE TITLE
WVUI got deprecated for Codex. Please update codebase.

### ISSUE THREAD

**Issue by Volker-E** [snapwiki/SnapWikiSkin#135]
Similar issue as Cosmos skin https://phabricator.wikimedia.org/T319239:

With [T310243: deprecating WVUI in favor of Codex](https://phabricator.wikimedia.org/T310243), all products using [WVUI](https://phabricator.wikimedia.org/tag/wvui/) should replace their usage with [Codex](https://phabricator.wikimedia.org/tag/codex/)

Snap!WikiSkin uses WVUI (derived) code in a number of places.

'wvui-search' is replaced by '@wikimedia/codex-search' now.

**Comment by R4356th** [comment]
Thanks for informing us.
