### ISSUE TITLE
Templates and case-sensitivity are leading to fatals

### ISSUE THREAD

**Issue by jdlrobson** [snapwiki/snapwikiskin#28]
The templates in the skin reference a partial`Nav` but in the folder there is only a `nav` (note lowercase). This leads to fatals on operating systems where case matters:
https://skins-demo.wmflabs.org//wiki/Help:Sample_page?useformat=desktop&useskin=snapwikiskin

**Comment by R4356th** [comment]
Fixed! Thank you!
