### ISSUE TITLE
Release Version 1.0.0

### ISSUE THREAD

**Issue by R4356th** [snapwiki/snapwikiskin#3]
Pre-release checklist:
- [x] Add viewport - Assigned to @R4356th, likely only possible via PHP - Actually done in skin.json with help from Alistair3149
- [x] Add [Stylelint](https://github.com/wikimedia/stylelint-config-wikimedia) - Assigned to @GrahamSH-LLK
- [x] Fix rendering issue in the footer - Assigned to @GrahamSH-LLK 
- [x] Configure Dependabot - Done by @R4356th and @GrahamSH-LLK 
- [x] Make skin.mustache as small as possible by moving code to partials - Assigned to @R4356th 
- [x] [EPIC] Remove any unnecessary styling, classes and ids as well as duplicate ones to make sure unnecessary code is not shipped
- [x] Recheck if we are using semantic HTML5 tags - Assigned to @R4356th 
- [x] Recheck if the classes and ids are the same as most other skins (mostly Vector) - Assigned to @R4356th 
- [x] Investigate a build step that minifies all templates - Assigned to @R4356th
- [x] Show search suggestions (#8) - Assigned to @GrahamSH-LLK 
- [x] [SPIKE] Remove obsolete vendor prefixes (see https://phabricator.wikimedia.org/T278670 and https://phabricator.wikimedia.org/T266866) - Being done by @R4356th 
- [x] Add CI for PHP - Assigned to @R4356th 
- [x] Look into adding [Fresnel](https://github.com/wikimedia/fresnel) ([Wikitech documentation](https://wikitech.wikimedia.org/wiki/Performance/Fresnel)) - Assigned to @R4356th 
- [x] [EPIC] [DEV] Fix all Stylelint errors - Assigned to @GrahamSH-LLK and @R4356th 
- [x] Write a proper README
- [x] Create new `stable` branch
- [x] Publish a GitHub release

Post-release checklist:
- [x] Create MediaWiki.org documentation page
- [x] Make task for security review on Miraheze

**Comment by GrahamSH-LLK** [comment]
Viewport? WDYM?

**Comment by R4356th** [comment]
> 
> 
> Viewport? WDYM?

``<meta name=viewport``... ?

**Comment by GrahamSH-LLK** [comment]
@R4356th https://github.com/prettier/stylelint-config-prettier will let us turn off conflicting rules with Stylelint

**Comment by R4356th** [comment]
> 
> 
> @R4356th https://github.com/prettier/stylelint-config-prettier will let us turn off conflicting rules with Stylelint

Cool! Could you configure that, please?

**Comment by R4356th** [comment]
@GrahamSH-LLK, please see the most recently added task about Vue template compilation.

**Comment by R4356th** [comment]
Declining the idea of adding Fresnel as it seems overkill.

**Comment by R4356th** [comment]
I wil probably work on minification when everything else is done.

**Comment by R4356th** [comment]
Removed the item about PWA as it is indeed not a blocker and I am working on it slowly separately inside an extension.

**Comment by R4356th** [comment]
Getting rid of the legacy ResourceLoader module feature may take time and needs to be done very carefully as it may introduce regressions. We can do this after the release, too, if we find ourselves in a hurry (our anniversary is in just 8 days!).

**Comment by R4356th** [comment]
Same for obsolete vendor prefixes.

**Comment by R4356th** [comment]
I have dealt with all Stylelint errors! 🥳

**Comment by R4356th** [comment]
Oops.

**Comment by R4356th** [comment]
All dev work done! 🚀

**Comment by R4356th** [comment]
Will get to the documentation part tonight hopefully.

**Comment by R4356th** [comment]
Documentation and security review task created!
