### ISSUE TITLE
Could not find partial `Nav` at skins/snapwikiskin/templates/minified//Nav.mustache

### ISSUE THREAD

**Issue by jdlrobson** [snapwiki/snapwikiskin#41]
```
 Original exception: [9d5f6900829fca73135f78fd] /wiki/Help:Sample_page?useformat=desktop&useskin=snapwikiskin RuntimeException: Could not compile template `skin`: Could not find partial `Nav` at skins/snapwikiskin/templates/minified//Nav.mustache
```

Am seeing this on both main and stable branches. The Mustache parser is case sensitive so I think this is just a case of selecting which is the preferred.

**Comment by R4356th** [comment]
I renamed the partials in #29 so this is not related to case. The error message includes two slashes in front of Nav.mustache so that should be the cause. This seems like an issue in MW master to me.

**Comment by jdlrobson** [comment]
I did a fresh install and it seems to be working again. I suspect the operating system ignore the case changes.
```
rf -rf snapwikiskin
git clone https://github.com/snapwiki/snapwikiskin.git
```
